"""Data models for the unified refine agent.

These models drive the refinement loop by providing requirements
extracted during analysis and identifying hotspots that need special attention.
"""

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, Field


class Hotspot(BaseModel):
    """Known trouble area requiring special attention during refinement.

    Hotspots are identified during analysis and represent elements like
    figures, tables, or complex layouts that typically need AI-assisted
    verification or transcription.
    """

    page: int = Field(..., description="1-indexed page number")
    element_type: Literal["figure", "table", "complex"] = Field(
        ..., description="Type of element"
    )
    bbox: tuple[float, float, float, float] = Field(
        ..., description="Bounding box (l, t, r, b) in document coordinates"
    )
    description: str = Field(
        ..., description="Brief description of the element for context"
    )
    verification_hint: str = Field(
        default="",
        description="Hint for verification (e.g., 'Check axis labels on chart')",
    )


class Requirements(BaseModel):
    """Requirements generated by analyze phase to drive refinement.

    These requirements provide the refine agent with document-specific
    context and success criteria for verification.
    """

    document_type: str = Field(
        ..., description="Classification (e.g., 'syllabus', 'lecture notes', 'exam')"
    )
    expected_headings: list[str] = Field(
        default_factory=list,
        description="Expected heading structure based on document type",
    )
    expected_figures: int = Field(
        default=0, description="Expected number of figures/images"
    )
    expected_tables: int = Field(default=0, description="Expected number of tables")
    key_terms: list[str] = Field(
        default_factory=list,
        description="Domain-specific terms for OCR validation",
    )
    hotspots: list[Hotspot] = Field(
        default_factory=list,
        description="Identified trouble areas needing special attention",
    )
    style_conventions: str = Field(
        default="",
        description="Observed style conventions (e.g., 'numbered sections', 'bullet lists')",
    )


class Correction(BaseModel):
    """A single correction made during the refinement process.

    Used by the v3 correction pipeline to track edits with full provenance.
    Lighter-weight than EditPatch for the simple composable editing tools.
    """

    page: int = Field(..., description="Page number this correction applies to (1-indexed)")
    edit_type: str = Field(
        ..., description="Category of edit (e.g., 'ocr_fix', 'formatting', 'alt_text')"
    )
    original: str = Field(..., description="Original text that was replaced")
    corrected: str = Field(..., description="New text that replaced it")
    reasoning: str = Field(..., description="Why this correction was made")
    confidence: float = Field(
        default=1.0, ge=0.0, le=1.0, description="Confidence in this correction"
    )
    source: str = Field(
        default="execution_agent",
        description="What produced this correction (e.g., 'execution_agent', 'lint', 'spell')",
    )


class EditType(str, Enum):
    """Category of edit for tracking and analysis."""

    LINT_FIX = "lint_fix"  # Auto-applied formatting fix
    SPELL_FIX = "spell_fix"  # OCR artifact correction
    FIGURE_ALT = "figure_alt"  # Alt-text for figure
    TABLE_TRANSCRIPTION = "table_transcription"  # Table markdown
    HEADING_FIX = "heading_fix"  # Heading level/text correction
    READING_ORDER = "reading_order"  # Reading order correction
    CONTENT_FIX = "content_fix"  # General content correction
    VERIFICATION_FIX = "verification_fix"  # Fix from image verification
    MANUAL = "manual"  # Human-requested edit


class EditPatch(BaseModel):
    """Structured representation of an edit with full provenance."""

    reasoning: str = Field(..., description="Why this edit was made (first, most important)")
    edit_type: EditType = Field(..., description="Category of edit")
    original_section: str = Field(..., description="Original markdown text to replace")
    modified_section: str = Field(..., description="New markdown text")
    page: int = Field(..., description="Page number this edit applies to")
    confidence: float = Field(
        default=1.0, ge=0.0, le=1.0, description="Confidence in this edit"
    )
    source: str = Field(
        default="refine_agent", description="What produced this edit (agent, lint, spell, subagent)"
    )


class RefineResult(BaseModel):
    """Result from a single page refinement iteration."""

    page: int = Field(..., description="Page number that was refined")
    markdown: str = Field(..., description="Refined markdown for this page")
    edits_applied: list[EditPatch] = Field(
        default_factory=list, description="Edits made during refinement"
    )
    lint_issues_fixed: int = Field(default=0, description="Number of lint issues fixed")
    spelling_corrections: int = Field(
        default=0, description="Number of spelling corrections"
    )
    subagent_calls: int = Field(
        default=0, description="Number of subagent tool calls made"
    )
    verification_passed: bool = Field(
        default=False, description="Whether verification against image passed"
    )


class ProcessingTrace(BaseModel):
    """Trace of the full processing pipeline for debugging and cost tracking."""

    phases: list[str] = Field(default_factory=list, description="Phases executed")
    total_llm_calls: int = Field(default=0, description="Total LLM API calls")
    total_input_tokens: int = Field(default=0, description="Total input tokens")
    total_output_tokens: int = Field(default=0, description="Total output tokens")
    estimated_cost_usd: float = Field(default=0.0, description="Estimated cost in USD")
    page_results: list[RefineResult] = Field(
        default_factory=list, description="Per-page refinement results"
    )
    errors: list[str] = Field(default_factory=list, description="Any errors encountered")

    # Edit history - all edits across all pages with full provenance
    edit_history: list[EditPatch] = Field(
        default_factory=list,
        description="Complete history of all edits made during processing",
    )

    def add_edit(self, edit: EditPatch) -> None:
        """Add an edit to the history."""
        self.edit_history.append(edit)

    def get_edits_by_type(self, edit_type: EditType) -> list[EditPatch]:
        """Get all edits of a specific type."""
        return [e for e in self.edit_history if e.edit_type == edit_type]

    def get_edits_by_page(self, page: int) -> list[EditPatch]:
        """Get all edits for a specific page."""
        return [e for e in self.edit_history if e.page == page]

    @property
    def edit_summary(self) -> dict[str, int]:
        """Get count of edits by type."""
        from collections import Counter
        return dict(Counter(e.edit_type.value for e in self.edit_history))
