"""Deterministic pre-analysis layer for document accessibility (PRD-012).

This package provides deterministic tools for detecting accessibility issues
before expensive LLM processing:

- VeraPDF: PDF/UA-1 accessibility validation (WCAG 2.x mapping)
- PyMarkdown: Markdown structure linting (heading hierarchy, alt text)

The hints generated by these analyzers guide specialist agents to focus
on specific issues, reducing wasted tokens and improving accuracy.

Usage:
    >>> from src.analyzers import HintsCacheService
    >>> service = HintsCacheService()
    >>> cache = await service.analyze_document(
    ...     document_id="job-123",
    ...     pdf_path="/path/to/doc.pdf",
    ...     page_markdowns={1: "# Title\\n\\nContent..."}
    ... )
    >>> print(f"Found {cache.total_hints} hints")

Components:
    HintsCacheService: Main orchestration service
    PDFAccessibilityAnalyzer: VeraPDF wrapper for PDF/UA validation
    MarkdownLinter: PyMarkdown wrapper for markdown structure
"""

from .hints_cache import HintsCacheService
from .markdown_linter import MarkdownLinter
from .pdf_accessibility_analyzer import PDFAccessibilityAnalyzer

__all__ = [
    "HintsCacheService",
    "MarkdownLinter",
    "PDFAccessibilityAnalyzer",
]
