"""Observation models for the remediation pipeline.

Observations are the atomic unit of the remediation pipeline. They represent
discrepancies between visual presentation and semantic markup, generated by:
- Analysis agent (initial document scan)
- Specialized agents (figures, tables, structure, typography)
- Human reviewers (manual observations)
"""

from datetime import UTC, datetime
from typing import Literal
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field

# Valid observation status transitions
VALID_OBSERVATION_TRANSITIONS: dict[str, list[str]] = {
    "open": ["resolved", "wont_fix", "manual"],
    "resolved": [],      # Terminal state
    "wont_fix": [],      # Terminal state
    "manual": ["resolved", "wont_fix"],  # Can be resolved later
}


class ObservationLocation(BaseModel):
    """Location reference for an observation.

    Identifies where in the document an observation applies. Supports three
    location types for different use cases:
    - element: CSS-like selector for specific element
    - range: Line range in markdown (e.g., "10-15")
    - region: Human-readable description of region

    Attributes:
        location_type: Type of location reference
        value: The actual location reference (selector, range, or description)
        page_num: 1-indexed page number where observation occurs

    Example:
        >>> loc = ObservationLocation(
        ...     location_type="element",
        ...     value="img[alt='']",
        ...     page_num=3
        ... )
    """

    location_type: Literal["element", "range", "region"] = Field(
        default="region",
        description="Type of location reference"
    )
    value: str = Field(
        ...,
        min_length=1,
        description="Selector, line range, or region description"
    )
    page_num: int = Field(..., ge=1, description="1-indexed page number")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "location_type": "element",
                "value": "img[alt='']",
                "page_num": 3
            }
        }
    )


class Observation(BaseModel):
    """A discrepancy between visual presentation and semantic markup.

    Observations are the atomic unit of the remediation pipeline.
    They can be generated by:
    - Analysis agent (initial document scan)
    - Specialized agents (figures, tables, structure, typography)
    - Human reviewers (manual observations)

    Observations do NOT map directly to WCAG criteria - that mapping
    can be derived later for compliance reporting.

    Status Transitions:
        - open → resolved | wont_fix | manual
        - manual → resolved | wont_fix
        - resolved (terminal)
        - wont_fix (terminal)

    Attributes:
        id: UUID for this observation
        job_id: Associated job ID
        agent: Agent that created this observation
        source: Whether created by agent or human
        visual_description: What is visually presented in the PDF
        markup_description: How it's currently represented in markup
        location: Where in the document this applies
        confidence: Agent's confidence in this observation (0.0-1.0)
        severity: Impact severity (critical, major, minor)
        route: Whether this can be auto-fixed or needs manual review
        manual_reason: Why this needs human judgment (if route=manual)
        status: Current lifecycle status
        resolved_by: Proposal ID that resolved this (if resolved)
        created_at: When observation was created
        human_comment: Comment from human when submitting observation

    Example:
        >>> obs = Observation(
        ...     id="550e8400-e29b-41d4-a716-446655440000",
        ...     job_id="job-123",
        ...     agent="figures",
        ...     visual_description="Image shows flowchart with 5 steps",
        ...     markup_description="Image has empty alt text",
        ...     location=ObservationLocation(
        ...         location_type="element",
        ...         value="img[src='figure-1.png']",
        ...         page_num=3
        ...     ),
        ...     confidence=0.9,
        ...     severity="major"
        ... )
    """

    id: str = Field(
        default_factory=lambda: str(uuid4()),
        description="UUID for this observation"
    )
    job_id: str = Field(..., description="Associated job ID")

    # Source
    agent: str = Field(
        ...,
        description="Agent that created: analysis, figures, tables, structure, typography, human"
    )
    source: Literal["agent", "human"] = Field(
        default="agent",
        description="Whether created by AI agent or human reviewer"
    )

    # What the AI/human perceived
    visual_description: str = Field(
        ...,
        min_length=1,
        description="What is visually presented in the PDF"
    )
    markup_description: str = Field(
        ...,
        min_length=1,
        description="How it's currently represented in markup"
    )

    # Location
    location: ObservationLocation

    # Assessment
    confidence: float = Field(
        default=0.8,
        ge=0.0,
        le=1.0,
        description="Agent's confidence in this observation"
    )
    severity: Literal["critical", "major", "minor"] = Field(
        default="major",
        description="Impact severity of this observation"
    )

    # Routing
    route: Literal["auto", "manual"] = Field(
        default="auto",
        description="Whether this can be auto-fixed or needs manual review"
    )
    manual_reason: str | None = Field(
        default=None,
        description="Why this needs human judgment (if route=manual)"
    )

    # Lifecycle
    status: Literal["open", "resolved", "wont_fix", "manual"] = Field(
        default="open",
        description="Current lifecycle status"
    )
    resolved_by: str | None = Field(
        default=None,
        description="Proposal ID that resolved this observation"
    )

    # Metadata
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))

    # Optional: Human edit context
    human_comment: str | None = Field(
        default=None,
        description="Comment from human when submitting observation"
    )

    def can_transition_to(self, new_status: str) -> bool:
        """Check if transition to new status is valid.

        Args:
            new_status: Target status to transition to

        Returns:
            True if transition is allowed by state machine
        """
        valid_next = VALID_OBSERVATION_TRANSITIONS.get(self.status, [])
        return new_status in valid_next

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "id": "550e8400-e29b-41d4-a716-446655440000",
                "job_id": "job-123-uuid",
                "agent": "figures",
                "source": "agent",
                "visual_description": "Image shows a flowchart with 5 connected boxes showing registration process",
                "markup_description": "Image has empty alt text: ![](figure-1.png)",
                "location": {
                    "location_type": "element",
                    "value": "img[src='figure-1.png']",
                    "page_num": 3
                },
                "confidence": 0.92,
                "severity": "major",
                "route": "auto",
                "manual_reason": None,
                "status": "open",
                "resolved_by": None,
                "created_at": "2024-12-10T10:30:00Z",
                "human_comment": None
            }
        }
    )
