"""Observation models for the remediation pipeline.

Observations are the atomic unit of the remediation pipeline. They represent
discrepancies between visual presentation and semantic markup, generated by:
- Analysis agent (initial document scan)
- Specialized agents (figures, tables, structure, typography)
- Human reviewers (manual observations)

Lifecycle (simplified to 2 fields):
- status: "open" or "closed"
- resolution: "fixed", "kept_original", or "skipped" (only when closed)

The ProcessingTrace captures full details of who/when/how.
"""

from datetime import UTC, datetime
from typing import Literal
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field


class ObservationLocation(BaseModel):
    """Location reference for an observation.

    Identifies where in the document an observation applies. Supports three
    location types for different use cases:
    - element: CSS-like selector for specific element
    - range: Line range in markdown (e.g., "10-15")
    - region: Human-readable description of region

    Attributes:
        location_type: Type of location reference
        value: The actual location reference (selector, range, or description)
        page_num: 1-indexed page number where observation occurs

    Example:
        >>> loc = ObservationLocation(
        ...     location_type="element",
        ...     value="img[alt='']",
        ...     page_num=3
        ... )
    """

    location_type: Literal["element", "range", "region"] = Field(
        default="region",
        description="Type of location reference"
    )
    value: str = Field(
        ...,
        min_length=1,
        description="Selector, line range, or region description"
    )
    page_num: int = Field(..., ge=1, description="1-indexed page number")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "location_type": "element",
                "value": "img[alt='']",
                "page_num": 3
            }
        }
    )


class Observation(BaseModel):
    """A discrepancy between visual presentation and semantic markup.

    Observations are the atomic unit of the remediation pipeline.
    They can be generated by:
    - Analysis agent (initial document scan)
    - Specialized agents (figures, tables, structure, typography)
    - Human reviewers (manual observations)

    Observations do NOT map directly to WCAG criteria - that mapping
    can be derived later for compliance reporting.

    SIMPLIFIED LIFECYCLE (2 fields only):
    - status: "open" or "closed"
    - resolution: What was the outcome? (only set when closed)
        - "fixed": Correction was applied (auto or human)
        - "kept_original": Human chose to keep as-is
        - "skipped": Force-applied with unreviewed items

    The ProcessingTrace captures full details of who/when/how.

    Attributes:
        id: UUID for this observation
        job_id: Associated job ID
        agent: Agent that created this observation
        source: Whether created by agent or human
        visual_description: What is visually presented in the PDF
        markup_description: How it's currently represented in markup
        location: Where in the document this applies
        affected_pages: For issues spanning multiple pages
        confidence: Agent's confidence in this observation (0.0-1.0)
        severity: Impact severity (critical, major, minor)
        category: Category for grouping (single source of truth)
        status: "open" or "closed"
        resolution: Outcome when closed
        created_at: When observation was created
        human_comment: Comment from human when submitting observation

    Example:
        >>> obs = Observation(
        ...     job_id="job-123",
        ...     agent="figures",
        ...     visual_description="Image shows flowchart with 5 steps",
        ...     markup_description="Image has empty alt text",
        ...     location=ObservationLocation(
        ...         location_type="element",
        ...         value="img[src='figure-1.png']",
        ...         page_num=3
        ...     ),
        ...     category="alt_text",
        ...     confidence=0.9,
        ...     severity="major"
        ... )
    """

    # Identification
    id: str = Field(
        default_factory=lambda: str(uuid4()),
        description="UUID for this observation"
    )
    job_id: str = Field(..., description="Associated job ID")

    # Source
    agent: str = Field(
        ...,
        description="Agent that created: figures, tables, structure, typography"
    )
    source: Literal["agent", "human"] = Field(
        default="agent",
        description="Whether created by AI agent or human reviewer"
    )

    # What the AI/human perceived
    visual_description: str = Field(
        ...,
        min_length=1,
        description="What is visually presented in the PDF"
    )
    markup_description: str = Field(
        ...,
        min_length=1,
        description="How it's currently represented in markup"
    )

    # Location
    location: ObservationLocation
    affected_pages: list[int] = Field(
        default_factory=list,
        description="For issues spanning multiple pages"
    )

    # Assessment
    confidence: float = Field(
        default=0.8,
        ge=0.0,
        le=1.0,
        description="Agent's confidence in this observation"
    )
    severity: Literal["critical", "major", "minor"] = Field(
        default="major",
        description="Impact severity of this observation"
    )

    # Category for grouping (single source of truth - ReviewItem derives from this)
    category: str = Field(
        default="general",
        description="Category: reading_order, heading, ocr, formatting, alt_text, table, etc."
    )

    # SIMPLIFIED LIFECYCLE (2 fields only)
    # ProcessingTrace already captures who/when/how
    status: Literal["open", "closed"] = Field(
        default="open",
        description="Is this observation resolved?"
    )
    resolution: Literal["fixed", "kept_original", "skipped"] | None = Field(
        default=None,
        description="What was the outcome? Only set when status='closed'"
    )

    # Metadata
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    human_comment: str | None = Field(
        default=None,
        description="Comment from human when submitting observation"
    )

    def close(self, resolution: Literal["fixed", "kept_original", "skipped"]) -> None:
        """Close this observation with the given resolution.

        Args:
            resolution: The outcome
                - "fixed": Correction was applied (auto or human)
                - "kept_original": Human chose to keep as-is
                - "skipped": Force-applied with unreviewed items

        Raises:
            ValueError: If observation is already closed
        """
        if self.status == "closed":
            raise ValueError("Observation already closed")
        self.status = "closed"
        self.resolution = resolution

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "id": "550e8400-e29b-41d4-a716-446655440000",
                "job_id": "job-123-uuid",
                "agent": "figures",
                "source": "agent",
                "visual_description": "Image shows a flowchart with 5 connected boxes showing registration process",
                "markup_description": "Image has empty alt text: ![](figure-1.png)",
                "location": {
                    "location_type": "element",
                    "value": "img[src='figure-1.png']",
                    "page_num": 3
                },
                "affected_pages": [3],
                "confidence": 0.92,
                "severity": "major",
                "category": "alt_text",
                "status": "open",
                "resolution": None,
                "created_at": "2024-12-10T10:30:00Z",
                "human_comment": None
            }
        }
    )
